CREATE DATABASE PRIMECOOKIES 
USE PRIMECOOKIES;

--DROPS PURCHASES AND CLIENTS
IF OBJECT_ID ('TEMPDB ..CLIENT') IS NOT NULL DROP TABLE CLIENT
IF OBJECT_ID ('TEMPDB ..CLIENTINVOICE') IS NOT NULL DROP VIEW CLIENTINVOICE


--CREATES THE CLIENTS TABLE

CREATE TABLE CLIENT (

CLIENTID INT  PRIMARY KEY IDENTITY,

  CLIENTADDRESS VARCHAR(50) NOT NULL,
  CLIENTZIPCODE VARCHAR(15) NOT NULL,
  CLIENTCITY VARCHAR(20) NOT NULL, 
  CLIENTSTATE VARCHAR(20) NOT NULL,
  CLIENTFNAME VARCHAR(30) NOT NULL,
  CLIENTLNAME VARCHAR(30) NOT NULL,
  CLIENTPAYMENT MONEY NOT NULL DEFAULT  $0.00,
  CLIENTCELLPHONE VARCHAR(15),
  CLIENTHOMEPHONE  VARCHAR(15));

 
  --CREATES THE STAFF TABLE
  IF OBJECT_ID ('TEMPDB ..STAFF') IS NOT NULL DROP TABLE STAFF

  CREATE TABLE STAFF( STAFFID INT PRIMARY KEY IDENTITY, STAFFLNAME NVARCHAR(50),
  STAFFFNAME NVARCHAR(50), PHONENUMBER INT NOT NULL, STAFFADDRESS INT NOT NULL,
  STAFFSALARIES VARCHAR(120) NOT NULL, STAFFPOSITIONS NVARCHAR(40), STAFFHIRED NVARCHAR(30));

  --CREATE THE COOKIES TABLE
  IF OBJECT_ID ('TEMPDB ..COOKIE') IS NOT NULL DROP TABLE COOKIE

  CREATE TABLE COOKIE(

  COOKIESID INT PRIMARY KEY IDENTITY
  , COOKIESIZES VARCHAR(40), COOKIEFLAVORS NVARCHAR(50),
  CUSTOMCOOKIES VARCHAR NOT NULL, COOKIEPRICELIST INT NOT NULL);


  --CREATE CAKES TABLE
  IF OBJECT_ID ('TEMPDB .. CAKE') IS NOT NULL DROP TABLE CAKE

CREATE TABLE CAKE(
CAKESID INT PRIMARY KEY IDENTITY, CAKEFLAVORS VARCHAR(80), CAKEPRICELIST NVARCHAR(40));

--CREATE INVOICE TABLE
IF OBJECT_ID ('TEMPDB ..INVOICE') IS NOT NULL DROP TABLE INVOICE

CREATE TABLE INVOICE(
INVOICEID INT PRIMARY KEY IDENTITY, INVOICENO NVARCHAR(70));


 --CREATES THE PRIMECOOKIES TABLE PURCHASES TABLE
 IF OBJECT_ID('TEMPDB ..PURCHASE') IS NOT NULL DROP TABLE PURCHASE

  CREATE TABLE PURCHASE (

  PURCHASEID INT PRIMARY KEY IDENTITY, 

  CLIENTID INT FOREIGN KEY REFERENCES CLIENT(CLIENTID),
  
  COOKIESID INT FOREIGN KEY REFERENCES COOKIE(COOKIESID),
  
  CAKESID INT FOREIGN KEY REFERENCES CAKE(CAKESID),
  
  INVOICEID INT FOREIGN KEY  REFERENCES INVOICE(INVOICEID),

  QUANTITYCOOKIES MONEY NULL, QUANTITYCAKES MONEY NULL);

  --CREATES STORES TABLE
IF OBJECT_ID ('TEMPDB ..STORE') IS  NOT NULL DROP TABLE STORE
IF OBJECT_ID ('TEMPDB ..STORENUM') IS NOT NULL ALTER TABLE STORE DROP COLUMN STORENUM
 

CREATE TABLE STORE(
STOREID INT PRIMARY KEY IDENTITY,
STAFFID INT FOREIGN KEY REFERENCES STAFF(STAFFID),
STORENUM VARCHAR(200),
STORELOCATION VARCHAR(50));

-- CREATE DELIVERIES TABLES
IF OBJECT_ID ('TEMPDB ..DELIVERIES') IS NOT NULL DROP TABLE DELIVERIES
IF OBJECT_ID ('TEMPDB ..DELIVERYNUM') IS NOT NULL ALTER TABLE DELIVERIE DROP COLUMN DELIVERYNUM


CREATE TABLE DELIVERIES(
DELIVERYNO INT PRIMARY KEY IDENTITY,
INVOICEID INT FOREIGN KEY REFERENCES INVOICE(INVOICEID),
CLIENTID INT FOREIGN KEY REFERENCES CLIENT(CLIENTID),
PURCHASEID INT FOREIGN KEY REFERENCES PURCHASE(PURCHASEID),
STOREID INT FOREIGN KEY REFERENCES STORE(STOREID),
DELIVERYDATE NVARCHAR(50) NOT NULL, DELIVERYNUM NVARCHAR(90));





  --CREATES AN INDEX FOR FOREIGN KEY CLIENTSID ON PURCHASES --INDEXES PURCHASES FOR THE FOREIGN KEY CLIENTID
  CREATE INDEX IXCLIENTID 
  ON PURCHASE (CLIENTID);

  CREATE INDEX IXCOOKIE
  ON PURCHASE (COOKIESID);
  
  CREATE INDEX IX_CAKESID
  ON PURCHASE (CAKESID);

  CREATE INDEX IX_INVOICES
  ON PURCHASE (INVOICEID);

  CREATE INDEX IX_INVOICES
  ON DELIVERIES (INVOICEID);

  CREATE INDEX IX_CLIENT
  ON DELIVERIES (CLIENTID);

CREATE INDEX IX_PURCHASES
ON DELIVERIES (PURCHASEID);



  -- ALTERS TABLE TO ADD CLIENTSUBSCRIPTION

  ALTER TABLE CLIENT
  ADD CLIENTSUBSCRPITION NVARCHAR(400);

  --INSERTS ENTRIES INTO THE CLIENTS TABLE
  INSERT INTO CLIENT 
  (clientAddress, clientFName, 
  clientLName, clientZipCode, clientHomePhone,
  clientCity, clientState)
  VALUES ('1513 Complete Street','Keith', 'Berg', 
  '15223', '754-883-9274', 'PITTSBURGH', 'PENNSYLVANIA');

  INSERT INTO CLIENT ( clientAddress, 
  clientFName, clientLName, clientZipCode, clientCellPhone, clientCity, clientState)
VALUES ('1245 LINT DR, MCLEOD HILL','REBECCA', 'MOSS', 
'68012', '680-732-8896', 'OMAHA', 'NEBRASKA' );  

 INSERT INTO CLIENT
  (clientAddress, clientFName, 
  clientLName, clientZipCode, clientHomePhone,
  clientCity, clientState)
  VALUES ( '2712 ELMS STREET', 'EMILY', 'MARTINS', '23471', 
  '554-665-6895', 'CLEVELAND', 'OHIO');


  INSERT INTO CLIENT
  (clientAddress, clientFName, 
  clientLName, clientZipCode, clientHomePhone,
  clientCity, clientState)
  VALUES ( '3457 TRAILHEAD, RD', 'STEVEN', 'JOHNSON',
  '4444', '484-864-7921', 'ANN ARBOR', 'MICHIGAN'); 


  INSERT INTO CLIENT 
  (clientAddress, clientFName, 
  clientLName, clientZipCode, clientHomePhone,
  clientCity, clientState)
  VALUES( '651 DICK RD', 'MIGUEL', 'GRACIE', '14043', '347-558-7862', 'DEPEW', 'NEW YORK');
  

  INSERT INTO CLIENT 
  (clientAddress, clientFName, 
  clientLName, clientZipCode, clientHomePhone,
  clientCity, clientState)
  VALUES ('3715 E. HUTCHINSON AVE', 
  'FREDDIE', 'BASTARD', '13851', '412-866-9788', 'PITTSBURGH', 'PENNSYLVANIA');



  INSERT INTO CLIENT 
  (clientAddress, clientFName, 
  clientLName, clientZipCode, clientHomePhone,
  clientCity, clientState)
  VALUES ('879 KIMBER DR',
  'ANNE', 'BECKARD', '13214', '347-556-7985', 'DEWITT', 'NEW YORK');



  INSERT INTO CLIENT 
  (clientAddress, clientFName, 
  clientLName, clientZipCode, clientHomePhone,
  clientCity, clientState)
  VALUES ('2713 MCDOWELL ST', 
  'DUSTIN', 'VANDERBERG', '15212', '412-331-7645', 'PITTSBURGH', 'PENNSYLVANIA');

  INSERT INTO CLIENT 
  (clientAddress, clientFName, 
  clientLName, clientZipCode, clientHomePhone,
  clientCity, clientState)
  VALUES ( '786 DEERFIELD RD',
  'TRACEY', 'ANN-WOLL', '18436', '412-589-6612', 'MONROEVILLE', 'PENNSYLVANIA');



  INSERT INTO CLIENT 
  (clientAddress, clientFName, 
  clientLName, clientZipCode, clientHomePhone,
  clientCity, clientState)
  VALUES ( '128 LAKE ARIEL HWY', 'ELIZABETH', 'TURNER', '18436', '570-698-9232', 'NEBRASKA', 'PENNSYLVANIA');

  --INSERTS ENTRIES INTO THE PURCHASES TABLE

  INSERT INTO PURCHASE 
  (QUANTITYCOOKIES, QUANTITYCAKES)
  VALUES (12.00 , 0.00);

  
  INSERT INTO PURCHASE 
  (QUANTITYCOOKIES, QUANTITYCAKES)
  VALUES (26.00 , 5.00);


  INSERT INTO PURCHASE 
  (QUANTITYCOOKIES, QUANTITYCAKES)
  VALUES (22.00 , 4.00);


  INSERT INTO PURCHASE 
  (QUANTITYCOOKIES, QUANTITYCAKES)
  VALUES (32.00 , 1.00);


  INSERT INTO PURCHASE 
  (QUANTITYCOOKIES, QUANTITYCAKES)
  VALUES (3.00 , 1.00);


  INSERT INTO PURCHASE 
  (QUANTITYCOOKIES, QUANTITYCAKES)
  VALUES (21.00 , 4.00);


  INSERT INTO PURCHASE 
  (QUANTITYCOOKIES, QUANTITYCAKES)
  VALUES (30.00 , 4.00);


  INSERT INTO PURCHASE 
  (QUANTITYCOOKIES, QUANTITYCAKES)
  VALUES (0.00 , 6.00);


  INSERT INTO PURCHASE 
  (QUANTITYCOOKIES, QUANTITYCAKES)
  VALUES (12.00 , 12.00);


  INSERT INTO PURCHASE
  (QUANTITYCOOKIES, QUANTITYCAKES)
  VALUES (12.00 , 2.00);

  --INSERTS INTO THE COOKIE TABLE

  INSERT INTO COOKIE (COOKIESIZES, COOKIEFLAVORS, CUSTOMCOOKIES, COOKIEPRICELIST)
  VALUES ( 'LARGE 8INCHES', 'TRADITIONAL THUMBPRINT COOKIES', 'NONE ',  25.00 );

  INSERT INTO COOKIE (COOKIESIZES, COOKIEFLAVORS, CUSTOMCOOKIES, COOKIEPRICELIST)
  VALUES ('LARGE 7INCHES' , 'VANILLA', 'PEANUTBUTTER CHERRY FUDGE COOKIES',  29.99);

  INSERT INTO COOKIE (COOKIESIZES, COOKIEFLAVORS, CUSTOMCOOKIES, COOKIEPRICELIST)
  VALUES ( 'MEDIUM 5INCHES' , 'TRADITIONAL CHOCOLATE CHIP COOKIES', 'NONE ', 14.99 );
  
  INSERT INTO COOKIE (COOKIESIZES, COOKIEFLAVORS, CUSTOMCOOKIES, COOKIEPRICELIST)
  VALUES ( 'MEDIUM 4INCHES', 'LEMON COOKIES', 'ADD COCONUT SHAVINGS', 23.99 );
  
  INSERT INTO COOKIE (COOKIESIZES, COOKIEFLAVORS, CUSTOMCOOKIES, COOKIEPRICELIST)
  VALUES ( 'LARGE 7INCHES', 'RASPBERRY FILLED SNICKER DOODLE', 'SPRINKLED JALAPENO SEEDS',  18.99 );
  
  INSERT INTO COOKIE (COOKIESIZES, COOKIEFLAVORS, CUSTOMCOOKIES, COOKIEPRICELIST)
  VALUES ('SMALL 1INCHE', 'CINNAMON TADITIONAL COOKIES', ' NONE',  7.99 );
   
   INSERT INTO COOKIE (COOKIESIZES, COOKIEFLAVORS, CUSTOMCOOKIES, COOKIEPRICELIST)
  VALUES ( 'MEDUIM 5INCHES', 'CINNAMON', 'CINNAMON-BUN COOKIES',  18.99 );

  INSERT INTO COOKIE (COOKIESIZES, COOKIEFLAVORS, CUSTOMCOOKIES, COOKIEPRICELIST)
  VALUES ( 'SMALL 3INCHES', 'PEANUTBUTTER', 'BLUEBERRY PEANUTBUTTER FILLING',  19.99 );

  INSERT INTO COOKIE (COOKIESIZES, COOKIEFLAVORS, CUSTOMCOOKIES, COOKIEPRICELIST)
  VALUES ('SMALL 3INCHES', 'CHOCOLATE-CHIP', 'BALL COOKIE BITES ADD HAZELNUT FILLING',  23.99 );

  INSERT INTO COOKIE (COOKIESIZES, COOKIEFLAVORS, CUSTOMCOOKIES, COOKIEPRICELIST)
  VALUES ('SUPERBIG 24INCHES', 'SNICKER DOODLE', 'EIGHT BERRYGLAZE',  44.99 );

  INSERT INTO COOKIE (COOKIESIZES, COOKIEFLAVORS, CUSTOMCOOKIES, COOKIEPRICELIST)
  VALUES ('MEDIUM 4INCHES', 'SUGAR COOKIES', 'NONE',  4.99 );

  INSERT INTO COOKIE (COOKIESIZES, COOKIEFLAVORS, CUSTOMCOOKIES, COOKIEPRICELIST)
  VALUES ('MEDIUM 5INCHES', 'FUDGE', 'NONE', 4.99 );

  INSERT INTO COOKIE (COOKIESIZES, COOKIEFLAVORS, CUSTOMCOOKIES, COOKIEPRICELIST)
  VALUES ( 'BIG 10INCHES', 'LEMON', 'WARHEAD COOKIES',  23.99 );

  INSERT INTO COOKIE (COOKIESIZES, COOKIEFLAVORS, CUSTOMCOOKIES, COOKIEPRICELIST)
  VALUES ( 'MEDUIM 4INCHES', 'PUMPKIN COOKIES', 'ACIA FILLED COOKIES',  4.99 );

  INSERT INTO COOKIE (COOKIESIZES, COOKIEFLAVORS, CUSTOMCOOKIES, COOKIEPRICELIST)
  VALUES ( 'MEDIUM 5INCHES', 'CRUMBLE COOKIES', 'RASPBERRY CHEESECAKE',  10.99 );

  INSERT INTO COOKIE (COOKIESIZES, COOKIEFLAVORS, CUSTOMCOOKIES, COOKIEPRICELIST)
  VALUES ( 'MEDIUM 5INCHES', 'GINGER BREAD COOKIES', 'ADULT THEMED WITH GINGER BLUEBERRY GLAZE AND LEMON SHAVINGS', 50.99 );

  INSERT INTO COOKIE (COOKIESIZES, COOKIEFLAVORS, CUSTOMCOOKIES, COOKIEPRICELIST)
  VALUES ( 'SMALL 2INCHES', 'FRENCH MACARONS', 'GRANOLAH BATTERED COOKIES', 5.99 );

  INSERT INTO COOKIE (COOKIESIZES, COOKIEFLAVORS, CUSTOMCOOKIES, COOKIEPRICELIST)
  VALUES ( 'MEDIUM 6INCHES','LEMON ORANGE', 'FINELY SOFTBAKED', 13.99 );

  --INSERT ENTRIES INTO CAKE TABLE

  INSERT INTO CAKE
  (CAKEFLAVORS, CAKEPRICELIST)
  VALUES ( 'RASPBERRY WITH STRAWBERRY FROSTING',  30.00);

  
  INSERT INTO CAKE
  (CAKEFLAVORS, CAKEPRICELIST)
  VALUES ( 'CHOCOLATE WITH STRAWBERRY GINGER FROSTING',  35.00);

 
  INSERT INTO CAKE
  (CAKEFLAVORS, CAKEPRICELIST)
  VALUES ( 'BLUEBERRY WIITH CINNAMON-BUN DESIGN AND LIGHT SWEET ICING',  30.00);

  
  INSERT INTO CAKE
  (CAKEFLAVORS, CAKEPRICELIST)
  VALUES ( 'VANILLA WITH STRAWBERRY CARAMEL FILLING CENTER MEDIUM BITTER',  34.00);

  
  INSERT INTO CAKE
  (CAKEFLAVORS, CAKEPRICELIST)
  VALUES ( 'ALCOHOL ICING WITH GREEN APPLE CAKE, MULTILAYERED CAKE',  50.00);

  
  INSERT INTO CAKE
  (CAKEFLAVORS, CAKEPRICELIST)
  VALUES ( 'MYSTERY FLAVOR CAKE WITH SPECIALTY CANDY GLAZE',  45.00);

  --INSERT INTO STAFF TABLE

  INSERT INTO STAFF 
  (STAFFFNAME, STAFFLNAME, PHONENUMBER, STAFFADDRESS, STAFFSALARIES, STAFFPOSITIONS, STAFFHIRED)
  VALUES ( 'MARIA', 'NEIMANN', '412-313-2895', '1513 FORSYTH STREET', '$80,000', 'GENERAL MANAGER', '2011-04-07' );

  INSERT INTO STAFF 
  (STAFFFNAME, STAFFLNAME, PHONENUMBER, STAFFADDRESS, STAFFSALARIES, STAFFPOSITIONS, STAFFHIRED)
  VALUES ( 'CHRISTOPHER', 'DOWNS', '347-125-8944', '1211 HAMELTON RD','$48,000','BAKER LEAD', ' 2015-11-03'  );

  INSERT INTO STAFF 
  (STAFFFNAME, STAFFLNAME, PHONENUMBER, STAFFADDRESS, STAFFSALARIES, STAFFPOSITIONS, STAFFHIRED)
  VALUES ( 'ELIZABETH', 'NELSON', '412-319-1823', '156 WOODSTOCK RD', '$50,000', 'BAKER LEAD', '2019-07-08' );

  INSERT INTO STAFF
  (STAFFFNAME, STAFFLNAME, PHONENUMBER, STAFFADDRESS, STAFFSALARIES, STAFFPOSITIONS, STAFFHIRED)
  VALUES ( ' STEPHANIE', 'BARTUS', '741-885-1911', '324 FOXRUN DRIVE', '$60,000', 'MANAGER', '2012-12-12'  );

INSERT INTO STAFF
  (STAFFFNAME, STAFFLNAME, PHONENUMBER, STAFFADDRESS, STAFFSALARIES, STAFFPOSITIONS, STAFFHIRED)
  VALUES (  'CHARLES', 'VANDERBERG', '412-331-8855', '1223 WOODSRUN AVE', '$40,000', 'BAKER', '2016-08-09');


  INSERT INTO STAFF
  (STAFFFNAME, STAFFLNAME, PHONENUMBER, STAFFADDRESS, STAFFSALARIES, STAFFPOSITIONS, STAFFHIRED)
  VALUES ( 'MICHELLE', 'SIMMS', '741-238-7695', '356 HELLIER, KY', '$41,000', 'BAKER', '2019-12-09');


  INSERT INTO STAFF 
  (STAFFFNAME, STAFFLNAME, PHONENUMBER, STAFFADDRESS, STAFFSALARIES, STAFFPOSITIONS, STAFFHIRED)
  VALUES (  'MICHAEL', 'ANGELOS', '843-911-1030', '1345 LIBERTY ST', '$41,000', 'BAKER', '18-04-13');

  INSERT INTO STAFF 
  (STAFFFNAME, STAFFLNAME, PHONENUMBER, STAFFADDRESS, STAFFSALARIES, STAFFPOSITIONS, STAFFHIRED)
  VALUES ( 'SUSAN', 'WESTON', '781-129-3054', '168 LIGHTRUN AVE', '$50,000', 'HEAD BAKER', '2015-05-16' );

  INSERT INTO STAFF 
  (STAFFFNAME, STAFFLNAME, PHONENUMBER, STAFFADDRESS, STAFFSALARIES, STAFFPOSITIONS, STAFFHIRED)
  VALUES ( 'MADISON', 'REGAN', '741-129-8054', '177 REEDSDALE STREET', '$50,000', 'HEAD DRIVER BAKER', '2011-05-16' );

  INSERT INTO STAFF 
  (STAFFFNAME, STAFFLNAME, PHONENUMBER, STAFFADDRESS, STAFFSALARIES, STAFFPOSITIONS, STAFFHIRED)
  VALUES ( 'HAROLD', 'RAINFOOT', '481-129-8054', '167 DEETS-VIEW AVE', '$44,000', 'DRIVER BAKER', '2012-05-06' );

  INSERT INTO STAFF 
  (STAFFFNAME, STAFFLNAME, PHONENUMBER, STAFFADDRESS, STAFFSALARIES, STAFFPOSITIONS, STAFFHIRED)
  VALUES ( 'THOMAS', 'LUGHTNER', '741-129-8054', '1677 REEDS RUN AVE', '$41,000', 'DRIVER BAKER', '2016-04-16' );

  INSERT INTO STAFF 
  (STAFFFNAME, STAFFLNAME, PHONENUMBER, STAFFADDRESS, STAFFSALARIES, STAFFPOSITIONS, STAFFHIRED)
  VALUES ( 'THOMAS', 'LUGHTNER', '741-129-8054', '1677 REEDS RUN AVE', '$40,000', 'DRIVER BAKER', '2018-07-16' );

  INSERT INTO STAFF 
  (STAFFFNAME, STAFFLNAME, PHONENUMBER, STAFFADDRESS, STAFFSALARIES, STAFFPOSITIONS, STAFFHIRED)
  VALUES ( 'THOMAS', 'LUGHTNER', '741-129-8054', '1677 REEDS RUN AVE', '$45,000', 'DRIVER BAKER', '2018-05-16' );

--INSERT INVOICES TABLE
INSERT INTO INVOICE (INVOICENO)
VALUES( '184556' );

INSERT INTO INVOICE (INVOICENO)
VALUES( '184116' );

INSERT INTO INVOICE (INVOICENO)
VALUES( '184656' );

INSERT INTO INVOICE (INVOICENO)
VALUES( '181156' );

INSERT INTO INVOICE (INVOICENO)
VALUES( '194586' );

INSERT INTO INVOICE (INVOICENO)
VALUES( '117556' );

INSERT INTO INVOICE (INVOICENO)
VALUES( '178596' );

INSERT INTO INVOICE (INVOICENO)
VALUES( '191916' );

INSERT INTO INVOICE (INVOICENO)
VALUES( '1977846' );

INSERT INTO INVOICE (INVOICENO)
VALUES( '184576' );

INSERT INTO INVOICE (INVOICENO)
VALUES( '196306' );

INSERT INTO INVOICE (INVOICENO)
VALUES( '180056' );

INSERT INTO INVOICE (INVOICENO)
VALUES( '1812126' );

INSERT INTO INVOICE (INVOICENO)
VALUES( '1841876' );

INSERT INTO INVOICE (INVOICENO)
VALUES( '19857956' );

INSERT INTO INVOICE (INVOICENO)
VALUES( '1833156' );

INSERT INTO INVOICE (INVOICENO)
VALUES( '1849966' );

INSERT INTO INVOICE (INVOICENO)
VALUES( '19689556' );

--INSERT INTO DELIVERIES
INSERT INTO DELIVERIES(DELIVERYNUM, DELIVERYDATE)
VALUES ('12AC-445-8889-0C', '12DAYS');

INSERT INTO DELIVERIES(DELIVERYNUM, DELIVERYDATE)
VALUES ('1A3C-445-8889-0C', '5DAYS');
 
INSERT INTO DELIVERIES(DELIVERYNUM, DELIVERYDATE)
VALUES ('1A5C-445-8879-0C', '5DAYS');

INSERT INTO DELIVERIES(DELIVERYNUM, DELIVERYDATE)
VALUES ('62AC-445-8589-0C', '4DAYS');

INSERT INTO DELIVERIES(DELIVERYNUM, DELIVERYDATE)
VALUES ('82AC-445-8119-0C', '3DAYS');

INSERT INTO DELIVERIES(DELIVERYNUM, DELIVERYDATE)
VALUES ('13AC-445-8899-0C', '2DAYS');

INSERT INTO DELIVERIES(DELIVERYNUM, DELIVERYDATE)
VALUES ('1A4C-445-6889-0C', '3DAYS');

INSERT INTO DELIVERIES(DELIVERYNUM, DELIVERYDATE)
VALUES ('19AC-445-8289-0C', '2DAYS');

INSERT INTO DELIVERIES(DELIVERYNUM, DELIVERYDATE)
VALUES ('18AC-445-8689-0C', '5DAYS');

INSERT INTO DELIVERIES(DELIVERYNUM, DELIVERYDATE)
VALUES ('1A7C-445-8389-0C', '3DAYS');

INSERT INTO DELIVERIES(DELIVERYNUM, DELIVERYDATE)
VALUES ('1A9C-445-6189-0C', '7DAYS');

INSERT INTO DELIVERIES(DELIVERYNUM, DELIVERYDATE)
VALUES ('15AC-445-8769-0C', '5DAYS');

INSERT INTO DELIVERIES(DELIVERYNUM, DELIVERYDATE)
VALUES ('1A5C-445-7859-0C', '4DAYS');

INSERT INTO DELIVERIES(DELIVERYNUM, DELIVERYDATE)
VALUES ('11AC-445-1189-0C', '8DAYS');


--INSERT INTO STORE TABLE

INSERT INTO STORE(STORENUM, STORELOCATION)
VALUES ('19001', 'PENNSYLVANIA' );


INSERT INTO STORE(STORENUM, STORELOCATION)
VALUES ('201991', 'NEW YORK' );


INSERT INTO STORE(STORENUM, STORELOCATION)
VALUES ( '30447', 'NEBRASKA');


INSERT INTO STORE(STORENUM, STORELOCATION)
VALUES ( '404041', 'NEW JERSEY');


INSERT INTO STORE(STORENUM, STORELOCATION)
VALUES ( '66778', 'KENTUCKY' );


INSERT INTO STORE(STORENUM, STORELOCATION)
VALUES ('877456', 'VIRGINIA' );

-- THIS VIEW SHOWS COOKIES BOUGHT OVER CAKES IMPORTANT BECAUSE IT TRACKS POPULAIRTY
GO

CREATE VIEW  CUSTOMERS AS 
 
 (SELECT PURCHASEID, QUANTITYCOOKIES , QUANTITYCAKES , 

QUANTITYCOOKIES-QUANTITYCAKES AS TOTALCBOUGHT 

FROM PURCHASE

WHERE  QUANTITYCOOKIES > QUANTITYCAKES);

--the view tracks the deliveries WHERE THE PURCHASE IS 30.00 WITH ITS INVOICE
GO
CREATE VIEW CLIENTINVOICE AS

    (SELECT  CLIENTFNAME, CLIENTLNAME, (CLIENTFNAME+' '+CLIENTLNAME) AS CLIENTLIST, PURCHASE.QUANTITYCOOKIES

FROM INVOICE, PURCHASE AS PURCHASED

FULL JOIN PURCHASE ON PURCHASE.INVOICEID = PURCHASE.INVOICEID
FULL JOIN CLIENT ON PURCHASE.PURCHASEID = CLIENT.CLIENTID

WHERE	PURCHASE.QUANTITYCOOKIES = 30.00 AND INVOICE.INVOICENO = '1849966'); 
 
-- THIS VIEW SHOWS THE MANAGER AND THEIR OPERATING LOCATION THIS IS IMPORTANT BECAUSE IT IS THE LOCATION WHERE THE GOODS COME FROM
--

GO

CREATE VIEW [STAFF]  AS (

SELECT STAFF.STAFFFNAME, STAFF.STAFFLNAME, STAFF.STAFFPOSITIONS, STORE.STORELOCATION, (STAFFFNAME+' '+STAFFLNAME) AS STAFFFULNAME


FROM STAFF

JOIN STORE ON STORE.STAFFID = STAFF.STAFFID

WHERE STAFF.STAFFPOSITIONS = 'MANAGER' AND STAFF.STAFFSALARIES = '$60,000' AND STORE.STORELOCATION = 'VIRGINIA' );

GO

USE PRIMECOOKIES;

--UPDATES A STORE LOCATION IF  THE VIRGINA LOCATION EXIST ADD A NEW LOCATION TO STORE



IF EXISTS ( SELECT 1  FROM STORE WHERE STORELOCATION = 'VIRGINIA')
 
 UPDATE [STORE] 

 SET STORELOCATION = 'OHIO'

INSERT INTO STORE(STORENUM) 
 
 VALUES ('888945')

GO

--ADDS A TRANSACTIONS FROM A CLIENTS AND ADDS THE NECESSARY INFORMATION

USE PRIMECOOKIES;

DECLARE @BOUGHT MONEY;
DECLARE @BOUGHTDATE VARCHAR(50);
DECLARE @COOKIEBUY VARCHAR(60);
DECLARE @BOUGHTNAME NVARCHAR(50);
DECLARE @CAKEBUY  VARCHAR(50);
DECLARE @BOUGHTINVOICE NVARCHAR(40);
DECLARE @BOUGHTDELIVERYNO NVARCHAR(40);
DECLARE @BUYER INT;
DECLARE @DETAILS NVARCHAR(80);
DECLARE @DELIVENUM  INT;
DECLARE @ERRORCODE INT;

SET @BOUGHT = 43.99;
 SET @BOUGHTDATE = '2022-11-08'
 SET @COOKIEBUY = 'LEMON ORANGE SOFT BAKED'; --WHAT WAS BOUGHT
 SET @CAKEBUY = 13.99; 
 SET @BUYER = 5;
 SET @DELIVENUM = 4;
 

	SET @DETAILS = '$43.99 DUE'--SETS THE COST OF THE GOODS

BEGIN TRAN boughtGOODS;

UPDATE [PURCHASE] 
SET QUANTITYCOOKIES = @BOUGHT;

UPDATE [DELIVERIES]
SET DELIVERYDATE = @BOUGHTDATE, DELIVERYNUM = @DELIVENUM;

SELECT @ERRORCODE = @@ERROR
IF (@ERRORCODE != 0) GOTO ERROR --IF THERE IS A ERROR PRINT THE ERROR

 COMMIT TRAN;

 --WHEN ERROR OCCURS
 ERROR:
 IF (@ERRORCODE != 0) BEGIN
	PRINT 'AN ERROR HASD OCCURED' + @ERRORCODE;
	PRINT 'REFRESH AFTER A MINUTE AND TRY AGAIN';
	ROLLBACK TRAN 
END
ELSE PRINT 'TRANSACTIONS HAVE COMPLETED';

--ADDS A TRIGGER THAT SETS THE DELIVERYDATE TO TODAYS DATE WHEN THE COOKIE IS CHOCOLATE CHIP AND THE CAKE IS CHERRY 

USE PRIMECOOKIES;
GO 

CREATE TRIGGER SETDELIVERYDATE ON DELIVERIES 

FOR INSERT

AS BEGIN

UPDATE DELIVERIES
SET DELIVERYDATE =(GETDATE())
WHERE CLIENTFNAME = ( SELECT CLIENTFNAME + ', '+CLIENTLNAME FROM inserted)
END;
GO

INSERT INTO COOKIE (COOKIESIZES, COOKIEFLAVORS, CUSTOMCOOKIES, COOKIEPRICELIST)
  VALUES ('SMALL 4INCHES', 'CHOCOLATE-CHIP', 'BALL COOKIE BITES ADD HAZELNUT FILLING',  24.99 );


	INSERT INTO CAKE (CAKEFLAVORS, CAKEPRICELIST)
  VALUES ( 'CHERRY ICING WITH GREEN APPLE CAKE, MULTILAYERED CAKE',  40.00);

